apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlops-api
spec:
  selector:
    matchLabels:
      app: mlops-api
  endpoints:
    - port: http
      path: /metrics/
      interval: 15s
